name: Build and Deploy
on:
    push:
        branches:
            - master
        paths:
            - 'src/**'

jobs:
    buildAndDeploy:
        name: Build and deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@master
            - name: Install Dependencies
              run: yarn install --frozen-lockfile
            - name: Build
              run: yarn build
            - name: Deploy to Firebase
              uses: w9jds/firebase-action@master
              with:
                  args: deploy --only hosting
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_HOUSINGSTRATEGY }}
